apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    openshift.io/display-name: lab-storage
    argocd.argoproj.io/sync-wave: "5"
  labels:
    opendatahub.io/dashboard: "true"
  name: lab-storage
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  volumeMode: Filesystem
