kind: Deployment
apiVersion: apps/v1
metadata:
  name: llamastack-deployment
spec:
  template:
    spec:
      containers:
        - name: llamastack
          env:
            - name: OPENAI_API_KEY
              valueFrom:
                secretKeyRef:
                  key: OPENAI_API_KEY
                  name: openai-secret
            - name: LLM_AS_JUDGE_MODEL
              value: openai/gpt-4o
