apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
  # llama-serve resources
  - ../../../mcp-servers/slack-mcp

patchesStrategicMerge:
  - remove-tavily-env.yaml
  - patch-lab-bench-repo.yaml
