apiVersion: kubeflow.org/v1
kind: Notebook
metadata:
  name: lab
spec:
  template:
    spec:
      initContainers:
      - name: repo-clone
        image: alpine/git:latest
        command:
        - /bin/sh
        - -c
        - |
          echo "Cloning repository..."
          git clone https://github.com/opendatahub-io/llama-stack-demos.git /tmp/repo

          echo "Copying notebooks to persistent storage..."
          mkdir -p /workspace/
          cp -r /tmp/repo/demos/rag_agentic/notebooks/* /workspace/
          cp -r /tmp/repo/demos/rag_agentic/lab-container/requirements.txt /workspace/
          mkdir /workspace/src
          mkdir /workspace/images
          cp -r /tmp/repo/demos/rag_agentic/src/utils.py /workspace/src/
          cp -r /tmp/repo/demos/rag_agentic/src/client_tools.py /workspace/src/
          cp -r /tmp/repo/.env.example /workspace/.env
          echo "Notebook files copied successfully!"
        volumeMounts:
        - name: lab-storage
          mountPath: /workspace
