apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../namespace
  - ../../llama-stack
  - ../../notebooks

  # mcp-servers resources
  - ../../mcp-servers/openshift-mcp
