# I installed the secret in  namespace: llama-serve ( which is where the llama stack demos has llama stack deployment running)
kind: Secret
apiVersion: v1
metadata:
  name: maas-env-secret
data:
  MAAS_API_TOKEN: N..2E=
  MAAS_MODEL_NAME: bGxhbWEtNC1zY291dC0xN2ItMTZlLXc0YTE2
  MAAS_URL: aHR0cHM6Ly9sbGFtYS00LXNjb3V0LTE3Yi0xNmUtdzRhMTYtbWFhcy1hcGljYXN0LXByb2R1Y3Rpb24uYXBwcy5wcm9kLnJob2FpLnJoLWFpc2VydmljZXMtYnUuY29tOjQ0My92MQ==
type: Opaque